name: scoreboardapp
description: Example app for Flutter learning sessions

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.4
  hive: 1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  cupertino_icons: ^0.1.3

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/